# Default values for AURELI.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Frontend Deployment
frontend:
  metadata:
    name: frontend
  replicaCount: 2
  containerName: frontend-container
  image:
    repository: olumayor99/aureli-frontend
    pullPolicy: Always
    selectorLabels:
      app: frontend
    labels:
      app: frontend

# Backend Deployment
backend:
  metadata:
    name: backend
  replicaCount: 2
  containerName: backend-container
  image:
    repository: olumayor99/aureli-backend
    pullPolicy: Always
    selectorLabels:
      app: backend
    labels:
      app: backend

# Frontend Service
frontendService:
  name: frontend-service
  selector:
    app: frontend
  type: ClusterIP

# Backend Service
backendService:
  name: backend-service
  selector:
    app: backend
  type: ClusterIP

# Frontend Horizontal Pod Autoscaler
frontendHPA:
  minReplicas: 2
  maxReplicas: 5
  averageUtilization: 90

# Backendend Horizontal Pod Autoscaler
backendHPA:
  minReplicas: 2
  maxReplicas: 5
  averageUtilization: 90

# ExternalDNS
externalDNS:
  domainFilter: drayco.com
  txtOwnerID: Z00354553BB8KX3K62IM5
  
# Frontend Configmap
frontendCMData:
  REACT_APP_BACKEND_URL: /api/message
