# Default values for AURELI.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Frontend Deployment
frontend:
  metadata:
    name: frontend
  replicaCount: 2
  containerName: frontend-container
  image:
    repository: olumayor99/aureli-frontend
    pullPolicy: Always
    selectorLabels:
      app: frontend
    labels:
      app: frontend

# Backend Deployment
backend:
  metadata:
    name: backend
  replicaCount: 2
  containerName: backend-container
  image:
    repository: olumayor99/aureli-backend
    pullPolicy: Always
    selectorLabels:
      app: backend
    labels:
      app: backend

# Frontend Service
frontendService:
  name: frontend-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: drayco.com
  selector:
    app: frontend
  type: LoadBalancer

# Backend Service
backendService:
  name: backend-service
  selector:
    app: backend
  type: ClusterIP

# Frontend Horizontal Pod Autoscaler
frontendHPA:
  minReplicas: 2
  maxReplicas: 100
  averageUtilization: 10

# Backendend Horizontal Pod Autoscaler
backendHPA:
  minReplicas: 2
  maxReplicas: 100
  averageUtilization: 10

# ExternalDNS
externalDNS:
  domainFilter: drayco.com
  txtOwnerID: Z046868710106H7HIXYYF
  
# Frontend Configmap
frontendCMData:
  BACKEND_URL: http://backend-service/api/message
