# GRAFANA

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-grafana
      protocol: HTTP
    hosts:
    - grafana.w3krypto.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: istio-system
spec:
  hosts:
    - grafana.w3krypto.com
  gateways:
  - grafana-gateway
  http:
    - match:
      - uri:
          prefix: /?
      route:
      - destination:
          host: grafana.istio-system.svc.cluster.local
          port:
            number: 3000
        weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: grafana-dr
  namespace: istio-system
spec:
  host: grafana.istio-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

---
# TRACING

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tracing-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-tracing
      protocol: HTTP
    hosts:
    - jaeger.w3krypto.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tracing-vs
  namespace: istio-system
spec:
  hosts:
    - jaeger.w3krypto.com
  gateways:
  - tracing-gateway
  http:
    - match:
      - uri:
          prefix: /jaeger
      route:
      - destination:
          host: tracing.istio-system.svc.cluster.local
          port:
            number: 80
        weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tracing-dr
  namespace: istio-system
spec:
  host: tracing.istio-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

---
# PROMETHEUS

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: prometheus-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-prom
      protocol: HTTP
    hosts:
    - prom.w3krypto.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-vs
  namespace: istio-system
spec:
  hosts:
    - prom.w3krypto.com
  gateways:
  - prometheus-gateway
  http:
    - match:
      - uri:
          prefix: /graph
      route:
      - destination:
          host: prometheus.istio-system.svc.cluster.local
          port:
            number: 9090
        weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: prometheus-dr
  namespace: istio-system
spec:
  host: prometheus.istio-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

---
# KIALI

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kiali-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-kiali
      protocol: HTTP
    hosts:
    - kiali.w3krypto.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-vs
  namespace: istio-system
spec:
  hosts:
    - kiali.w3krypto.com
  gateways:
  - kiali-gateway
  http:
    - match:
      - uri:
          prefix: /kiali
      route:
      - destination:
          host: kiali.istio-system.svc.cluster.local
          port:
            number: 20001
        weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kiali-dr
  namespace: istio-system
spec:
  host: kiali.istio-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

---
# FRONTEND

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: frontend-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-frontend
      protocol: HTTP
    hosts:
    - frontend.w3krypto.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-vs
  namespace: istio-system
spec:
  hosts:
    - frontend.w3krypto.com
  gateways:
  - frontend-gateway
  http:
    - match:
      - uri:
          prefix: /
      rewrite:
        uri: /
      route:
      - destination:
          host: frontend-service.default.svc.cluster.local
          port:
            number: 80
        weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend-dr
  namespace: istio-system
spec:
  host: frontend-service.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

---
# BACKEND

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: backend-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-backend
      protocol: HTTP
    hosts:
    - backend.w3krypto.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend-vs
  namespace: istio-system
spec:
  hosts:
    - backend.w3krypto.com
  gateways:
  - backend-gateway
  http:
    - match:
      - uri:
          prefix: /api/message
      route:
      - destination:
          host: backend-service.default.svc.cluster.local
          port:
            number: 80
        weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend-dr
  namespace: istio-system
spec:
  host: backend-service.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

---
# LITMUS

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: litmus-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-litmus
      protocol: HTTP
    hosts:
    - litmus.w3krypto.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: litmus-vs
  namespace: istio-system
spec:
  hosts:
    - litmus.w3krypto.com
  gateways:
  - litmus-gateway
  http:
    - match:
      - uri:
          prefix: /login
      route:
      - destination:
          host: litmus-chaos-frontend-service.litmus.svc.cluster.local
          port:
            number: 9091
        weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: litmus-dr
  namespace: istio-system
spec:
  host: litmus-chaos-frontend-service.litmus.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE