apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontendService.name }}
spec:
  selector:
    {{- range $key, $val := .Values.frontendService.selector }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: {{ .Values.frontendService.type }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backendService.name }}
spec:
  selector:
    {{- range $key, $val := .Values.backendService.selector }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: {{ .Values.backendService.type }}
