name: Build and Push Docker Images to Repositories

on:
  push:
    branches: ["master", "main"]
    paths: ["backend/**", "frontend/**"]
  pull_request:
    branches: ["master", "main"]
    paths: ["backend/**", "frontend/**"]

jobs:
  build-and-push:
    name: Build App and Push to Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Frontend Docker image
        run: |
          cd frontend-aureli/
          docker build -t olumayor99/aureli-frontend .

      - name: Build Backend Docker image
        run: |
          cd backend-aureli/
          docker build -t olumayor99/aureli-backend .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push olumayor99/aureli-frontend
          docker push olumayor99/aureli-backend
